### ISSUE TITLE
Problems with transparency slider within the LayerManagement

### ISSUE THREAD

**Issue by jacmendt** [slub/slub_web_kartenforum#31]
## Summary

Currently the transparency slider shows odd behavior if the user move the cursor out of the _LayerEntry_. 

## Platforms:

* Chromium (Version 102.0.5005.61 (Official Build) snap (64-bit))

## How to reproduce

* Select two layers
* Start change transparency for one layer and move cursor away to the other layer entry

**Comment by jacmendt** [comment]
@NicolasLooschen can you please check if this bug is still present in the current release version. See also https://kartenforum.slub-dresden.de. If not please close this issue.

**Comment by NicolasLooschen** [comment]
Currently, the opacity slider behaves in such a way that the overlay over the layer management entry remains active as long as the mouse button is held down.

If the mouse button is released over the LayerManagement entry, it remains active.
If the mouse button is released over another part of the application, the overlay disappears, but the selected transparency remains.

https://user-images.githubusercontent.com/23079775/184586391-fab7edf0-f8a4-4795-ac23-a03bc39b33f0.mp4


From my point of view, this fixes the problem.
